name: daily-build

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/hankehly/browserbots:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Start VPN container
        run: |
          docker run -d \
            --cap-add=NET_ADMIN \
            --name vpn-japan \
            -e USER=${{ secrets.NORDVPN_EMAIL }} \
            -e PASS=${{ secrets.NORDVPN_PASSWORD }} \
            -e CONNECT=Japan \
            -e TECHNOLOGY=NordLynx ghcr.io/bubuntux/nordvpn

          # Todo: Replace with some sort of healthcheck
          echo "Wait 3 seconds to allow VPN to become healthy.."
          sleep 3

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: pointi.dailyclick
        run: |
          docker run --rm -v "${{ github.workspace }}/screenshots:/app/screenshots" \
            --network="container:vpn-japan" ghcr.io/hankehly/browserbots:latest python /app/browserbots/pointi/dailyclick.py \
            --email ${{ secrets.POINTI_EMAIL }} \
            --password ${{ secrets.POINTI_PASSWORD }} \
            --headless \
            --no-sandbox

      - name: pointi.magazine
        run: |
          docker run --rm -v "${{ github.workspace }}/screenshots:/app/screenshots" \
            --network="container:vpn-japan" ghcr.io/hankehly/browserbots:latest python /app/browserbots/pointi/magazine.py \
            --email ${{ secrets.POINTI_EMAIL }} \
            --password ${{ secrets.POINTI_PASSWORD }} \
            --headless \
            --no-sandbox

      - name: honeygain.honeyjar
        run: |
          docker run --rm -v "${{ github.workspace }}/screenshots:/app/screenshots" \
            ghcr.io/hankehly/browserbots:latest python /app/browserbots/honeygain/honeyjar.py \
            --email ${{ secrets.HONEYGAIN_EMAIL }} \
            --password ${{ secrets.HONEYGAIN_PASSWORD }} \
            --headless \
            --no-sandbox

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: screenshots
          path: ${{ github.workspace }}/screenshots
          if-no-files-found: 'ignore'
