name: pointi-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  run_daily_job:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run
        run: |
          # You're running into the same problem as this guy
          # https://stackoverflow.com/questions/68794334/github-action-with-selenium-and-docker
          docker run --rm ghcr.io/hankehly/browserbots:latest python /app/browserbots/pointi/pointi.py \
            --email ${{ secrets.POINTI_EMAIL }} \
            --password ${{ secrets.POINTI_PASSWORD }} \
            --no-sandbox
