name: pointi-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  run_daily_job:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run
        run: |
          # You're running into the same problem as this guy
          # https://stackoverflow.com/questions/68794334/github-action-with-selenium-and-docker
          mkdir -p ${{ github.workspace }}/screenshots
          docker run --rm -v "${{ github.workspace }}/screenshots:/app/screenshots" \
            --network host ghcr.io/hankehly/browserbots:latest python /app/browserbots/pointi/pointi.py \
            --email ${{ secrets.POINTI_EMAIL }} \
            --password ${{ secrets.POINTI_PASSWORD }} \
            --headless \
            --no-sandbox \
            --page-load-strategy normal
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: pointi-daily-screenshots
          path: ${{ github.workspace }}/screenshots
          if-no-files-found: 'ignore'

