name: pointi-daily

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: "false"
  schedule:
    - cron: '0 8 * * *'

jobs:
  run_daily_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/hankehly/browserbots:latest

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Test run
        run: |
          docker run --rm -d \
            --cap-add=NET_ADMIN \
            --name nordvpn \
            -e USER=${{ secrets.NORDVPN_EMAIL }} \
            -e PASS=${{ secrets.NORDVPN_PASSWORD }} \
            -e CONNECT=Japan
            -e TECHNOLOGY=NordLynx ghcr.io/bubuntux/nordvpn

          mkdir -p ${{ github.workspace }}/screenshots

          docker run --rm -v "${{ github.workspace }}/screenshots:/app/screenshots" \
            --network container:nordvpn ghcr.io/hankehly/browserbots:latest python /app/browserbots/pointi/pointi.py \
            --email ${{ secrets.POINTI_EMAIL }} \
            --password ${{ secrets.POINTI_PASSWORD }} \
            --headless \
            --no-sandbox

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: pointi-daily-screenshots
          path: ${{ github.workspace }}/screenshots
          if-no-files-found: 'ignore'

